{% set name = "easing-functions" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/easing_functions-{{ version }}.tar.gz
  sha256: e18c7931d445b85f28c4d15ad0a9a47bb65d4e2eefc0db3840448fae25e3f9de

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.0
    - pip
  run:
    - python >=3.0

test:
  imports:
    - easing_functions
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/semitable/easing-functions
  summary: A collection of the basic easing functions for python
  license: GPL-3.0-only
  license_file: LICENCE.md

extra:
  recipe-maintainers:
    - thewchan
